### ISSUE TITLE
Doesn't work with Roundcube 1.2

### ISSUE THREAD

**Issue by depoulo** [sblaisot/automatic_addressbook#10]
```
PHP Fatal error:  Call to undefined method rcube_imap::decode_address_list() in plugins/automatic_addressbook/automatic_addressbook.php on line 97
```

Can you fix this soon-ish? Otherwise I can try to work on a PR myself...

**Comment by sblaisot** [comment]
Hi @depoulo 

I don't know why you are reaching this old pre-0.8 compatibility code but there is something strange here.
in https://github.com/sblaisot/automatic_addressbook/blob/master/automatic_addressbook.php#L123 we check if the rcube_mime class exists and call this legacy code with rcube_imap if this is not the case.
I'm not aware of rcube_mime deprecation in 1.2 and automatic_addressbook is working fine on my server with rc 1.2-rc

I don't have time anymore to maintain automatic_addressbook but if you have fun to fix this, I'll be happy to merge your PR.

**Comment by depoulo** [comment]
My bad, I was using an outdated version of your plugin on that installation.
