### ISSUE TITLE
Roundcube bug after using this plugin for a while

### ISSUE THREAD

**Issue by Zenouque** [sblaisot/automatic_addressbook#12]
Hello, 
I installed this plugin one month ago on RC v1.2.2
I worked well until yesterday. Suddenly, all users of RC were unable to send messages anymore. 
(Actually , messages are sent but RC keeps the edited message page open and seems to be waiting for something. Then it says that an error hapenned. Ssent messages are not seen in 'sent messages' mailbox)

As it creates no messages in the roundcube logfiles, it took me a lot of time to solve this problem. I finally disabled the plugin in the RC config file and everything worked again.

I am available to perform tests and send logfiles if it can help to find the reason of the bug.

**Comment by Zenouque** [comment]
Some News:

This bug happens only when our LDAP server is unreachable.
I know that this plugin has nothing to do with LDAP, but he fact is that when I retablished the connection to the LDAP, roundcubes displayed no more error messages and sent messages are correctly listed in the mailbox.

**Comment by sblaisot** [comment]
Thanks you for your report and feedback.

Each time you send a mail, automatic_addressbook pluging looks through you address books and only stores the recipient if it doesn't exist in another addressbook. With ldap down, it can not perform the search and then can not send the mail. This explains the behaviour.

I don't see how to properly handle that kind of error better than failing to send the mail.

closing this bugreport now, but feel free to reopen it if needed.

**Comment by Zenouque** [comment]
I suggest that if the plugin cannot perform the search, it should only display no suggestions, just as roundcube behaves when the Ldap is down.
Roundcbube shall not hang, nor hide the message sent.
