### ISSUE TITLE
RC 1.2.3

### ISSUE THREAD

**Issue by bajlek** [sblaisot/automatic_addressbook#15]
Hello, your plugin does not wortk with RC 1.2.4 automatic address book is showing but there is no contact, also in DB there is no contact. I do it with your install instructions. Can you help me?

**Comment by 1mi** [comment]
It works in 1.2.7, but I had to add a table rc_collected_contacts whith my table prefix 'rc_' added to referenced table 'users' thus becoming 'rc_users'.
The query is in a file in the SQL directory of the plugin. Install instructions are found in INSTALL file of the plugin. Install instructions should be also mentioned on the plugin description page and in this github page.

**Comment by rmcaninch** [comment]
Version 0.4.3 on RC 1.2.3
The address is added to the collected address book. However, editing it does not move it to the personal addressbook as it used to. It stays in collected.

Edited to add: 0.4.2 gives an error dialog when it moves to the personal addressbook. I don't see anything logged to the roundcube/errors log for it.

**Comment by rmcaninch** [comment]
Disregard the first issue I mentioned. I have 0.4.3 working with 1.2.3. I still get an error dialog when the address is moved from the collected addresses to the default address book.
