### ISSUE TITLE
 Uncaught Error: Call to undefined function Q()

### ISSUE THREAD

**Issue by donkikhot** [sblaisot/automatic_addressbook#17]
Hi i am have this trouble on Roundcube Webmail 1.3.2 (PHP 7.0.22-0ubuntu0.16.04.1)
PHP Fatal error:  Uncaught Error: Call to undefined function Q() in /var/www/roundcube/plugins/automatic_addressbook/automatic_addressbook.php:81
i used composer install

**Comment by sblaisot** [comment]
Update your automatic_addressbook to 0.4.3 (last version) as this should be fixed. 
This has been fixed in #8

**Comment by donkikhot** [comment]
I have this version, but I understand you, thanks for the feedback!

**Comment by sblaisot** [comment]
It appears that the automatic_addressbook.php you are using is from an older version otherwise you wouldn't have any Q() on line 81.
