### ISSUE TITLE
saves only to Automatically Collected Addressbook

### ISSUE THREAD

**Issue by superinterstellar** [sblaisot/automatic_addressbook#2]
Hello,
It only saves email addresses to the automatically collected addressbook.
How do I make it save it back on the CardDAV(and not the automatically collected addresbook)?
Thanks
Kevin A.

**Comment by sblaisot** [comment]
Hi,

I'm not sure to understand what you get and what you want.
Do you mean that you want that addresses you send mail to be collected, but saved in your cardav addressbook ?

**Comment by superinterstellar** [comment]
Yes. In my carddav addessbook.

**Comment by superinterstellar** [comment]
Currently it saves in another address book called "automatically collected" address book

**Comment by sblaisot** [comment]
ok, so this is not a bug, this is the purpose of this plugin.

It collects mail addresses you send mail to and store them in an particular addressbook only used for autocompletion (and not in the main addressbook).
This plugin doesn't currently support any other backend than mysql or PostgreSQL database.

Feel free to implement another backend and submit a pull request.

**Comment by superinterstellar** [comment]
noted.
