### ISSUE TITLE
emails are not saving in Automatically collected address book

### ISSUE THREAD

**Issue by ashrafopl** [sblaisot/automatic_addressbook#21]
I have installed your automatic_addressbook plugin on my Roundcube 1.3.0. But this plugin is not working and my email addresses are not saving. Kindly please help me out with this problem. TIA

**Comment by vkuttyp** [comment]
It does work for me very well. Please make sure you did the following steps correctly as it is described here: https://github.com/sblaisot/automatic_addressbook/blob/master/INSTALL

wget https://github.com/sblaisot/automatic_addressbook/archive/0.4.3.tar.gz
 tar xvzf 0.4.3.tar.gz
 mv automatic_addressbook-0.4.3 automatic_addressbook
 chown -R www-data:www-data automatic_addressbook
 mv automatic_addressbook /var/www/mail/rc/plugins/

 add to rc/config/config.inc.php: 'automatic_addressbook',

**Comment by malcolmclark** [comment]
I also am not seeing emails saved in the custom address book. However, the 'Automatically Collected' address book now exits, but remains empty.

These are my install instructions:

cd <RC_root>/plugins
wget https://github.com/sblaisot/automatic_addressbook/archive/master.zip
unzip master.zip
mv automatic_addressbook-master automatic_addressbook
chown -R www-data:www-data automatic_addressbook
vi <RC_root>/config/config.inc.php
Append 'automatic_addressbook' to $config['plugins']  array.
cd <RC_root>/plugins/automatic_addressbook/config
cp config.inc.php.dist config.inc.php
mysql -uroot -p roundcube < mysql.initial.sql # And this has created a table which look exactly same as one of the other add books.

I'm not sure this instruction is correct:
$rcmail_config['plugins'] = array('automatic_addressbook',);
I decided it meant $config in the main RC config file....? See above.

As a sanity check I have successfully installed keyboard_shortcuts plugin to prove nothing fundamental is wrong.

Any help appreciated.

**Comment by malcolmclark** [comment]
And of course, I have sent emails to new recipients and received and replied to external email addresses.

M

**Comment by malcolmclark** [comment]
Solution:

**Removing 'example_addressbook' plugin**, which I was invited to install during RC setup.

It was also this plugin that was most annoyingly preventing me inputting a recipient email address and then tabbing through to the next input field. It would just overwrite what I had typed with somebody@example.com or similar. 

Alas, it's the usual necessary journey of making an acquaintance with the software and its debugging tools, logs etc  :)

M

**Comment by mehdid** [comment]
I am using Roundcube 1.1.5 and plugin at version 0.4.3. I have followed instructions described in INSTALL file as well hints given in this ticket. Unfortunately, it still doesn't work.

Any hint on how I can debug this situation?

**Comment by Steltek** [comment]
I can confirm the plugin works with the latest trunk version of RC.

- Did you import the mysql.initial.sql schema from the plugin into your Roundcube database? (Is the 'collected_contacts' table present in your database?)
- Did you look at the error logs in your Roundcube installation? Do they mention anything related to the plugin?

**Comment by dnoizeshakerz** [comment]
How do I execute the sqlite.initial.sql? Roundcube for Cpanel now uses SQL lite. But I have no idea how to execute it. Now basically I have done other parts, and the 'Automatically Collected' address book is already there in Roundcube. I just stuck in the step to execute the sqlite.initial.sql.

**Comment by rmcaninch** [comment]
I don't normally use sqlite. This appears to be how you would import a .sql file:
https://stackoverflow.com/questions/2049109/how-do-i-import-sql-files-into-sqlite-3
Assuming you can get to a command line on your cpanel.

**Comment by dnoizeshakerz** [comment]
> I don't normally use sqlite. This appears to be how you would import a .sql file:
> https://stackoverflow.com/questions/2049109/how-do-i-import-sql-files-into-sqlite-3
> Assuming you can get to a command line on your cpanel.

Thanks! Yeah, I already got it working.
