### ISSUE TITLE
Seems on_edit_move_to_default has no effect

### ISSUE THREAD

**Issue by cantoute** [sblaisot/automatic_addressbook#23]
Just did a fresh install of current roundcube and a git clone of this plugin.

It does save collected emails in it's "collected address book" but when one edits the contact, it stays there, and would be nice to be able to move collected emails into main contacts.

**Comment by sblaisot** [comment]
This is a preference in the config file.

**Comment by cantoute** [comment]
And that preference would move a contact to default when edited?
