### ISSUE TITLE
Can't get it working in rundcube 1.1.4

### ISSUE THREAD

**Issue by Ossipoff1290** [sblaisot/automatic_addressbook#6]
Cut not find the file <path_to_roundcube>/config/main.inc.php, 
But added automatic_addressbook to the file  <path_to_roundcube>/config/defaults.inc.php
// ----------------------------------
// PLUGINS
// ----------------------------------

// List of active plugins (in plugins/ directory)
$config['plugins'] = array('password', 'markasjunk2', 'sieverules','automatic_addressbook');

But it is still not working. 

other than me who can not get it to work?

**Comment by sblaisot** [comment]
`config/defaults.inc.php` is the defaults values (as shipped with roundcube).
Your configuration should be located in `config/config.inc.php`

please see http://trac.roundcube.net/wiki/Howto_Config#Defaultsforuserpreferences
