### ISSUE TITLE
Does it work with carddav plugin?

### ISSUE THREAD

**Issue by darkbasic** [sblaisot/automatic_addressbook#7]
https://github.com/blind-coder/rcmcarddav

Is it compatible?

**Comment by sblaisot** [comment]
Hi,

You can see #2 about that

this plugin doesn't have any interaction with any other addressbook backend plugin.
It only saves addresses you send mail to in the database (mysql or PostgreSQL) and use them as autocompletion source.
It doesn't store mail addresses in any other backend (carddav or ldap) nor uses addresses from any other source.

Feel free to contribute and implement other backends.
