### ISSUE TITLE
error while importing sql

### ISSUE THREAD

**Issue by suyashjain** [sblaisot/automatic_addressbook#9]
I am getting the following error while importing sql in mysql

ERROR 1005 (HY000): Can't create table 'vmail.collected_contacts' (errno: 150)

i believe , the foreign key is the issue

   REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,

table users does not exist.

**Comment by sblaisot** [comment]
Roundcube table `users` should exist.
https://github.com/roundcube/roundcubemail/blob/master/SQL/mysql.initial.sql#L20

If you don't have a `users` table in your roundcube database, then your roundcube installation is probably broken.
